#!/bin/sh

echo ""
echo "========================================================"
echo "================= TRY ADD LOGMINER USER ==================="
echo "========================================================"
echo ""

while getopts "u:p:" var
do
   case "$var" in
       u) NEW_LOGMINER_USER=${OPTARG};;
       p) NEW_LOGMINER_PWD=${OPTARG};;
   esac
done


echo ""
echo "++++++++++++ ENV List ++++++++++++"
echo "+++ ORACLE_PWD : ${ORACLE_PWD}"
echo "+++ NEW_LOGMINER_USER : ${NEW_LOGMINER_USER}"
echo "+++ NEW_LOGMINER_PWD : ${NEW_LOGMINER_PWD}"
echo "++++++++++++++++++++++++++++++++++"
echo ""

sqlplus sys/${ORACLE_PWD} as sysdba <<- EOF
  CREATE USER ${NEW_LOGMINER_USER} IDENTIFIED BY ${NEW_LOGMINER_PWD} DEFAULT TABLESPACE LOGMINER_TBS QUOTA UNLIMITED ON LOGMINER_TBS CONTAINER=ALL;

  GRANT CREATE SESSION TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SET CONTAINER TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SELECT ON V_\$DATABASE TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT FLASHBACK ANY TABLE TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SELECT ANY TABLE TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SELECT_CATALOG_ROLE TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT EXECUTE_CATALOG_ROLE TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SELECT ANY TRANSACTION TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SELECT ANY DICTIONARY TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT LOGMINING TO ${NEW_LOGMINER_USER} CONTAINER=ALL;

  GRANT CREATE TABLE TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT LOCK ANY TABLE TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT CREATE SEQUENCE TO ${NEW_LOGMINER_USER} CONTAINER=ALL;

  GRANT EXECUTE ON DBMS_LOGMNR TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT EXECUTE ON DBMS_LOGMNR_D TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SELECT ON V_\$LOGMNR_LOGS TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SELECT ON V_\$LOGMNR_CONTENTS TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SELECT ON V_\$LOGFILE TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SELECT ON V_\$ARCHIVED_LOG TO ${NEW_LOGMINER_USER} CONTAINER=ALL;
  GRANT SELECT ON V_\$ARCHIVE_DEST_STATUS TO ${NEW_LOGMINER_USER} CONTAINER=ALL;

  exit;
EOF

echo ""
echo "========================================================"
echo "================= DONE ADD LOGMINER USER ==============="
echo "========================================================"
echo ""